name: Continuous Integration

on:
  pull_request:
    branches: ['**', '!update/**', '!pr/**']
  push:
    branches: ['**', '!update/**', '!pr/**']
    tags: [v*]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Scala using Coursier
        uses: coursier/setup-action@v1
        with:
          apps: sbt
      - name: Scalafmt
        run: sbt scalafmtCheckAll
      - name: Run tests
        run: sbt coverage test
      - name: Coverage Report
        run: sbt coverageAggregate
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

  publish:
    needs: [test]
    if: github.event_name != 'pull_request' && (startsWith(github.ref, 'refs/tags/v'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Scala using Coursier
        uses: coursier/setup-action@v1
        with:
          apps: sbt
      - name: Publish ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ github.ref_name }}
        run: sbt "coverageOff;clean;compile;+publish"
